import type { SyntheticPatient } from '@/types/patient.types'

export const syntheticPatients: SyntheticPatient[] = [
  {
    id: 'patient-001',
    firstName: 'Maria',
    lastName: 'Gonzalez',
    dateOfBirth: '1985-03-14',
    memberId: '990122445',
    groupNumber: 'GRP001234',
    tradingPartnerServiceId: 'UNITEDHEALTHCARE',
    insurancePlan: 'UHC Gold PPO 2024',
    primaryCareProvider: 'Dr. Sarah Chen, MD',
    scenario: 'ELIGIBLE_ACTIVE',
    scenarioLabel: 'Active Coverage',
    narrativeContext: 'Maria is a 40-year-old project manager coming in for her annual physical. She has been with her employer for 6 years and has maintained continuous coverage. Her plan year started January 1 and she has not yet met her deductible.',
    subscriberFirstName: 'MARIA',
    subscriberLastName: 'GONZALEZ',
    subscriberDob: '19850314',
    npi: '1234567890',
    serviceTypeCode: '30',
  },
  {
    id: 'patient-002',
    firstName: 'James',
    lastName: 'Washington',
    dateOfBirth: '1972-08-22',
    memberId: '990133556',
    groupNumber: 'GRP005678',
    tradingPartnerServiceId: 'UNITEDHEALTHCARE',
    insurancePlan: 'UHC Platinum HMO 2024',
    primaryCareProvider: 'Dr. Michael Patel, DO',
    scenario: 'ELIGIBLE_DEDUCTIBLE_MET',
    scenarioLabel: 'Deductible Met',
    narrativeContext: 'James is a 53-year-old construction foreman who has already met his annual deductible after a knee surgery earlier this year. He is returning for a follow-up visit and physical therapy evaluation.',
    subscriberFirstName: 'JAMES',
    subscriberLastName: 'WASHINGTON',
    subscriberDob: '19720822',
    npi: '1234567890',
    serviceTypeCode: '30',
  },
  {
    id: 'patient-003',
    firstName: 'Aisha',
    lastName: 'Rahman',
    dateOfBirth: '1991-11-05',
    memberId: '990144667',
    groupNumber: 'GRP009012',
    tradingPartnerServiceId: 'UNITEDHEALTHCARE',
    insurancePlan: 'UHC Bronze HSA 2024',
    primaryCareProvider: 'Dr. Lisa Thompson, MD',
    scenario: 'ELIGIBLE_HIGH_COPAY',
    scenarioLabel: 'High Out-of-Pocket',
    narrativeContext: 'Aisha is a 34-year-old freelance graphic designer on a high-deductible health plan through the marketplace. She needs lab work for a thyroid condition but is concerned about costs. Her deductible is $3,000 and she has only used $200 so far this year.',
    subscriberFirstName: 'AISHA',
    subscriberLastName: 'RAHMAN',
    subscriberDob: '19911105',
    npi: '1234567890',
    serviceTypeCode: '30',
  },
  {
    id: 'patient-004',
    firstName: 'Robert',
    lastName: 'Chen',
    dateOfBirth: '1968-05-30',
    memberId: '990155778',
    groupNumber: 'GRP003456',
    tradingPartnerServiceId: 'UNITEDHEALTHCARE',
    insurancePlan: 'UHC Choice Plus PPO 2024',
    primaryCareProvider: 'Dr. Karen Williams, MD',
    scenario: 'INELIGIBLE_TERMED',
    scenarioLabel: 'Coverage Terminated',
    narrativeContext: 'Robert is a 57-year-old former IT director who was laid off two months ago. He is presenting his old insurance card not realizing his coverage terminated when his COBRA election period expired. He needs a prescription refill for blood pressure medication.',
    subscriberFirstName: 'ROBERT',
    subscriberLastName: 'CHEN',
    subscriberDob: '19680530',
    npi: '1234567890',
    serviceTypeCode: '30',
  },
  {
    id: 'patient-005',
    firstName: 'Destiny',
    lastName: 'Williams',
    dateOfBirth: '2001-09-17',
    memberId: '990166889',
    groupNumber: 'GRP007890',
    tradingPartnerServiceId: 'UNITEDHEALTHCARE',
    insurancePlan: 'UHC Student Health Plan',
    primaryCareProvider: 'Dr. David Kim, MD',
    scenario: 'INELIGIBLE_NOT_FOUND',
    scenarioLabel: 'Member Not Found',
    narrativeContext: 'Destiny is a 24-year-old graduate student who recently switched from her parents plan to a university-sponsored plan. She is presenting an old member ID that does not match any active records. The front desk needs to help her locate her new member ID.',
    subscriberFirstName: 'DESTINY',
    subscriberLastName: 'WILLIAMS',
    subscriberDob: '20010917',
    npi: '1234567890',
    serviceTypeCode: '30',
  },
  {
    id: 'patient-006',
    firstName: 'Thomas',
    lastName: "O'Brien",
    dateOfBirth: '1955-01-08',
    memberId: '990177990',
    groupNumber: 'GRP002345',
    tradingPartnerServiceId: 'UNITEDHEALTHCARE',
    insurancePlan: 'UHC Medicare Advantage PPO',
    primaryCareProvider: 'Dr. Angela Martinez, MD',
    scenario: 'ELIGIBLE_PENDING',
    scenarioLabel: 'Pending Verification',
    narrativeContext: 'Thomas is a 71-year-old retired teacher who recently enrolled in a Medicare Advantage plan during open enrollment. His coverage is showing as pending because the effective date has not yet been reached. He needs a wellness visit scheduled for next month.',
    subscriberFirstName: 'THOMAS',
    subscriberLastName: 'OBRIEN',
    subscriberDob: '19550108',
    npi: '1234567890',
    serviceTypeCode: '30',
  },
]
